---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-did-finder-girder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-did-finder-girder
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-did-finder-girder
    spec:
      containers:
      - name: {{ .Release.Name }}-did-finder-girder
        image: pondd/servicex-did-finder-girder:{{ .Values.didFinder.girder.tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: INSTANCE_NAME
            value: servicex
        args:
          - --rabbit-uri
          - amqp://user:leftfoot1@servicex-rabbitmq:5672
